#!/bin/bash
########################################################################
# LEARN-GIT SCRIPT
# CREATED   : EKO SAPUTRA (EVSYSTEM)
# DEV       : XENTA OS http://www.xentaos.org/
# LICENSE   : GNU GPL 3.0
# WEBSITE   : https://evsystemsite.wordpress.com
########################################################################

#upload-git

git init 
git add . 
git commit -m "first commit" 
git remote add origin https://github.com/ekovegeance/learn-git.git 
git push -u origin master
